#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: user
  password: password
  firstName: user
  
camunda.bpm:
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
    
   
spring:
   datasource: 
      url: jdbc:mysql://localhost:3306/loan_process
      username: root
      password: Ndovucloud@2020
      driver-class-name: com.mysql.jdbc.Driver
   
